import torch, warnings
from colosseum.networks.distributions import CategoricalDist, DiagGaussianDist, CompositeDist
torch.manual_seed(0)
logits = torch.randn(3, 4, requires_grad=True)
mask = torch.tensor([[1,1,0,0],[1,0,0,0],[0,0,0,0]], dtype=torch.bool)
print("== all-false mask row ==")
try:
    d = CategoricalDist(logits, mask)
    print("constructed; entropy", d.entropy())
except Exception as e:
    print("CategoricalDist with all-false row raised:", type(e).__name__, str(e)[:160])
print("== masked log_prob/entropy/grad, valid rows ==")
d = CategoricalDist(logits[:2], mask[:2])
lp = d.log_prob(torch.tensor([0, 0])); ent = d.entropy()
(lp.sum() + ent.sum()).backward()
print("log_prob", lp.detach(), "entropy", ent.detach(), "grad finite:", torch.isfinite(logits.grad).all().item())
print("== log_prob of a MASKED action ==")
logits2 = torch.randn(1, 4, requires_grad=True)
d = CategoricalDist(logits2, torch.tensor([[1,1,0,0]], dtype=torch.bool))
lp = d.log_prob(torch.tensor([3])); print("log_prob masked action:", lp.item())
lp.sum().backward(); print("grad:", logits2.grad)
print("== KL between two masked categorical dists ==")
a = CategoricalDist(torch.randn(2, 4), mask[:2]); b = CategoricalDist(torch.randn(2, 4), mask[:2])
print("KL(a||b) =", a.kl_divergence(b))
print("KL(a||unmasked b) =", a.kl_divergence(CategoricalDist(torch.randn(2,4))))
print("KL(unmasked a||masked b) =", CategoricalDist(torch.randn(2,4)).kl_divergence(b))
print("== DiagGaussian with multi-dim Box (B, 2, 3) ==")
g = DiagGaussianDist(torch.zeros(5, 2, 3), torch.zeros(5, 2, 3))
print("log_prob shape:", tuple(g.log_prob(torch.zeros(5, 2, 3)).shape), "(expected (5,)) action_dim:", g.action_dim)
print("== DiagGaussian log_std unbounded: log_std=30 ==")
g = DiagGaussianDist(torch.zeros(1, 1), torch.full((1, 1), 30.0))
print("sample:", g.sample().item(), "entropy:", g.entropy().item())
