# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from colosseum.transport import colosseum_pb2 as colosseum__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in colosseum_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeightStoreServiceStub(object):
    """=====================================================================
    Weight Store Service
    =====================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutWeights = channel.unary_unary(
                '/colosseum.WeightStoreService/PutWeights',
                request_serializer=colosseum__pb2.WeightPayloadProto.SerializeToString,
                response_deserializer=colosseum__pb2.PutWeightsResponse.FromString,
                _registered_method=True)
        self.GetWeights = channel.unary_unary(
                '/colosseum.WeightStoreService/GetWeights',
                request_serializer=colosseum__pb2.GetWeightsRequest.SerializeToString,
                response_deserializer=colosseum__pb2.WeightPayloadProto.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/colosseum.WeightStoreService/GetVersion',
                request_serializer=colosseum__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=colosseum__pb2.GetVersionResponse.FromString,
                _registered_method=True)


class WeightStoreServiceServicer(object):
    """=====================================================================
    Weight Store Service
    =====================================================================

    """

    def PutWeights(self, request, context):
        """Push new weights for an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeights(self, request, context):
        """Get latest weights for an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Get the current policy version for an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeightStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.PutWeights,
                    request_deserializer=colosseum__pb2.WeightPayloadProto.FromString,
                    response_serializer=colosseum__pb2.PutWeightsResponse.SerializeToString,
            ),
            'GetWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeights,
                    request_deserializer=colosseum__pb2.GetWeightsRequest.FromString,
                    response_serializer=colosseum__pb2.WeightPayloadProto.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=colosseum__pb2.GetVersionRequest.FromString,
                    response_serializer=colosseum__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'colosseum.WeightStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('colosseum.WeightStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeightStoreService(object):
    """=====================================================================
    Weight Store Service
    =====================================================================

    """

    @staticmethod
    def PutWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/colosseum.WeightStoreService/PutWeights',
            colosseum__pb2.WeightPayloadProto.SerializeToString,
            colosseum__pb2.PutWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/colosseum.WeightStoreService/GetWeights',
            colosseum__pb2.GetWeightsRequest.SerializeToString,
            colosseum__pb2.WeightPayloadProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/colosseum.WeightStoreService/GetVersion',
            colosseum__pb2.GetVersionRequest.SerializeToString,
            colosseum__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrajectoryServiceStub(object):
    """=====================================================================
    Trajectory Service (Workers → Learners)
    =====================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendChunks = channel.stream_unary(
                '/colosseum.TrajectoryService/SendChunks',
                request_serializer=colosseum__pb2.TrajectoryChunkProto.SerializeToString,
                response_deserializer=colosseum__pb2.SendChunksResponse.FromString,
                _registered_method=True)


class TrajectoryServiceServicer(object):
    """=====================================================================
    Trajectory Service (Workers → Learners)
    =====================================================================

    """

    def SendChunks(self, request_iterator, context):
        """Workers stream trajectory chunks to the learner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrajectoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendChunks': grpc.stream_unary_rpc_method_handler(
                    servicer.SendChunks,
                    request_deserializer=colosseum__pb2.TrajectoryChunkProto.FromString,
                    response_serializer=colosseum__pb2.SendChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'colosseum.TrajectoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('colosseum.TrajectoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrajectoryService(object):
    """=====================================================================
    Trajectory Service (Workers → Learners)
    =====================================================================

    """

    @staticmethod
    def SendChunks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/colosseum.TrajectoryService/SendChunks',
            colosseum__pb2.TrajectoryChunkProto.SerializeToString,
            colosseum__pb2.SendChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
