# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: colosseum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'colosseum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63olosseum.proto\x12\tcolosseum\"l\n\x12WeightPayloadProto\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x16\n\x0epolicy_version\x18\x02 \x01(\x05\x12\x18\n\x10state_dict_bytes\x18\x03 \x01(\x0c\x12\x12\n\ncompressed\x18\x04 \x01(\x08\"%\n\x12PutWeightsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x11GetWeightsRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"%\n\x11GetVersionRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\",\n\x12GetVersionResponse\x12\x16\n\x0epolicy_version\x18\x01 \x01(\x05\"r\n\x14TrajectoryChunkProto\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x1f\n\x17\x62\x65havior_policy_version\x18\x02 \x01(\x05\x12\x13\n\x0btensor_data\x18\x03 \x01(\x0c\x12\x12\n\ncompressed\x18\x04 \x01(\x08\"-\n\x12SendChunksResponse\x12\x17\n\x0f\x63hunks_received\x18\x01 \x01(\x05\x32\xf6\x01\n\x12WeightStoreService\x12J\n\nPutWeights\x12\x1d.colosseum.WeightPayloadProto\x1a\x1d.colosseum.PutWeightsResponse\x12I\n\nGetWeights\x12\x1c.colosseum.GetWeightsRequest\x1a\x1d.colosseum.WeightPayloadProto\x12I\n\nGetVersion\x12\x1c.colosseum.GetVersionRequest\x1a\x1d.colosseum.GetVersionResponse2c\n\x11TrajectoryService\x12N\n\nSendChunks\x12\x1f.colosseum.TrajectoryChunkProto\x1a\x1d.colosseum.SendChunksResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'colosseum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEIGHTPAYLOADPROTO']._serialized_start=30
  _globals['_WEIGHTPAYLOADPROTO']._serialized_end=138
  _globals['_PUTWEIGHTSRESPONSE']._serialized_start=140
  _globals['_PUTWEIGHTSRESPONSE']._serialized_end=177
  _globals['_GETWEIGHTSREQUEST']._serialized_start=179
  _globals['_GETWEIGHTSREQUEST']._serialized_end=216
  _globals['_GETVERSIONREQUEST']._serialized_start=218
  _globals['_GETVERSIONREQUEST']._serialized_end=255
  _globals['_GETVERSIONRESPONSE']._serialized_start=257
  _globals['_GETVERSIONRESPONSE']._serialized_end=301
  _globals['_TRAJECTORYCHUNKPROTO']._serialized_start=303
  _globals['_TRAJECTORYCHUNKPROTO']._serialized_end=417
  _globals['_SENDCHUNKSRESPONSE']._serialized_start=419
  _globals['_SENDCHUNKSRESPONSE']._serialized_end=464
  _globals['_WEIGHTSTORESERVICE']._serialized_start=467
  _globals['_WEIGHTSTORESERVICE']._serialized_end=713
  _globals['_TRAJECTORYSERVICE']._serialized_start=715
  _globals['_TRAJECTORYSERVICE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
